vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *vse
     steps:
        - attach_workspace:
           at: .
        - run:
           command: |
             ssh ubuntu@ec2-3-80-24-95.compute-1.amazonaws.com -oStrictHostKeyChecking=no '
             cd 4IT572_ansible/ansible/
             ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ec2_deploy.yml --user ubuntu --key-file devops.pem --vault-password-file password'

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
